### ISSUE TITLE
Cache bundle install on ruby applications

### ISSUE THREAD

**Issue by francomariani** [aws/elastic-beanstalk-roadmap#139]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Cache the bundle install to use `--local` flag if Gemfile is found as in AMI `/opt/elasticbeanstalk/hooks/appdeploy/pre/10_bundle_install.sh` 

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Nope.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'm trying to reduce the downtime of the deployment, I saw that what consumes most time is the command `/bin/sh -c bundle install` which does not takes into account if there's anything in `vendor/cache`.

**Are you currently working around this issue?**
Tried using the platform hook without success.

**Additional context**
Ruby 2.7 running on 64bit Amazon Linux 2/3.1.1 with Puma.

**Comment by ShaneBoyer** [comment]
My recent experience is that this works in Beanstalk AL2 (Ruby 2.6 on 3.2.1 in this case, so perhaps added for 3.2.x?).  If the ./vendor/cache folder contains cached gems, I see this output in the eb-engine.log:
`[INFO] Running command /bin/sh -c bundle install --local` and confirm there is no logged statement indicating it is contacting rubygems.org.  We achieved this using a `bundle cache` statement during our build process.  While this prevents calling out to the internet to retrieve gem sources, it does not significantly reduce deployment time due to local compilation.

If your deployment zip has the compiled gems for the deployment environment platform in ./vendor/bundle/[ruby version] (using something like `bundle config set --local path 'vendor/bundle'` prior to `bundle install`) then the deployment will use the compiled gems and not spend time compiling them from ./vendor/cache.  The major.minor ruby version must match on the build system (2.6.x in this case) and of course to do this you'll want to ensure the build system platform is the same as the deployed platform.

Hope this helps.

**Comment by januszm** [comment]
In the standard configuration, on AL2 deployment calls this

```
[INFO] Running command /bin/sh -c bundle config set --local deployment true
[INFO] Running command /bin/sh -c bundle install
```

But gems are apparently installed into  `vendor/bundle/ruby/2.x.0/gems` so they are lost with each deployment. I am not sure if this was the intention, but it is probably worth trying to install gems in a shared space (`/opt/elasticbeanstalk/.rbenv/` ?), so that at least as long as the same EC2 is running, you can use the cache.

**Comment by januszm** [comment]
Would it be possible to change the destination for installed gems from the application current directory (`vendor/bundle/ruby/2.x.0/gems`) to a shared location to  benefit from cache anytime soon?

Perhaps we could use `/var/app/containerfiles` for this?

**Comment by brendenyule** [comment]
There are platform hooks that run behind the scenes that you can't override now.
Here is what AWS support has to say on this issue when I asked them how to override the `bundle install` command:
```
01:38:37 PM Suruchi: So Beanstalk is designed this way, that it runs definite workflows in the backend for every command/operation. 
01:39:04 PM Suruchi: These workflows have definite set of scripts that are run as hook on every step of the workflow.
01:39:39 PM Suruchi: We cannot override those inbuilt commands of the workflow.
```

This is really inflexible, and is causing a lot of headaches for us.

**Comment by zzzhu0192** [comment]
Hi,

I explained how cache bundle install works on AL2 ruby platform in another issue. 

https://github.com/aws/elastic-beanstalk-roadmap/issues/183#issuecomment-914572812

please let me know if you still have questions.

**Comment by jsuarezb** [comment]
By running this line inside a platform hook under `.platform/hooks/prebuild/` I was able to use a folder outside the app directory to cache gems inside the instance, avoiding re-installation during each deploy.

```bash
bundle config set --local path <path outside app directory>
```

Env variables does not seem to work, so we need to use `bundle config` to set the installation path (outside the app directory).

Looks that I can keep using `BUNDLER_DEPLOYMENT_MODE=true` too with this approach, so seems pretty sane.

**Comment by januszm** [comment]
@jsuarezb  neat! I'll give it a try. Also add a confighook to keep the cache on Configuration deployments: `.platform/confighooks/prebuild/`

**Comment by toby5box** [comment]
> By running this line inside a platform hook under `.platform/hooks/prebuild/` I was able to use a folder outside the app directory to cache gems inside the instance, avoiding re-installation during each deploy.

This worked for me too. The steps were:

File `.platform/hooks/prebuild/00_packages.sh`:

```sh
#!/bin/bash

set -x

yum -y install https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-6-x86_64/postgresql12-libs-12.8-1PGDG.rhel6.x86_64.rpm || echo Skipped
yum -y install https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-6-x86_64/postgresql12-12.8-1PGDG.rhel6.x86_64.rpm || echo Skipped
yum -y install https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-6-x86_64/postgresql12-devel-12.8-1PGDG.rhel6.x86_64.rpm || echo Skipped

bundle config set --local path build/gems
```

And in `buildspec.yml`:

```yml
---
version: 0.1

phases:
  build:
    commands:
      - rbenv local 2.7.6
      - mkdir -p build/gems
      - bundle config set --local path build/gems
      - yum -y install https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-6-x86_64/postgresql12-libs-12.8-1PGDG.rhel6.x86_64.rpm || echo Skipped
      - yum -y install https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-6-x86_64/postgresql12-12.8-1PGDG.rhel6.x86_64.rpm || echo Skipped
      - yum -y install https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-6-x86_64/postgresql12-devel-12.8-1PGDG.rhel6.x86_64.rpm || echo Skipped
      - bundle config set build.pg --with-pg-config=/usr/pgsql-12/bin/pg_config
      - bundle install

artifacts:
  files:
    - "**/*"

```

(The postgresql packages are to work around a `pg` build issue.)

**Comment by januszm** [comment]
@toby5box  you can simplify the `pg` and bundler part with:

```
# File:  .ebextensions/01_packages.config
packages:
  yum:
    git: []
    htop: []
commands:
  setup_bundler:
    command: 'bundle config set --local path build/gems'
  update_packages:
    command: 'amazon-linux-extras install postgresql13'
```

ref: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html#linux-commands
