### ISSUE TITLE
Control and protection over leader instances

### ISSUE THREAD

**Issue by ScottHull** [aws/elastic-beanstalk-roadmap#148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
There are currently no means to protect leader instances or to identify which instance is the leader.  One must rebuild or deploy to the environment in order to create a leader instance in a multi-instance environment

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
No.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I am running a Django platform where it is desirable to have Celery asynchronous tasks only execute once on one server, rather than having the asynchronous tasks execute on every open instance.  I have found a method to start CeleryBeat on only the leader instance through `.ebextensions.`  However, auto-scaling environments exist under the threat of having the leader removed.  Moreover, the leader environment is not identifiable in the AWS EB dashboard or in the EB CLI (important for rebooting the instance or SSH'ing into the instance).

**Are you currently working around this issue?**
In `.ebextensions` I can start CeleryBeat on a the leader instance:

```
container_commands:
 01_killotherbeats:
   command: "ps auxww | grep 'celery beat' | awk '{print $2}' | sudo xargs kill -9 || true"
   ignoreErrors: true
 02_celery_tasks:
   command: "cat .ebextensions/files/celery_configuration.txt > /opt/elasticbeanstalk/hooks/appdeploy/post/run_supervised_celeryd.sh && chmod 744 /opt/elasticbeanstalk/hooks/appdeploy/post/run_supervised_celeryd.sh"
   leader_only: true
 03_celery_tasks_run:
   command: "/opt/elasticbeanstalk/hooks/appdeploy/post/run_supervised_celeryd.sh"
   leader_only: true
```
However, beyond this, no leader control is available.
