### ISSUE TITLE
New platform branch to support ECS-based docker running on AL2

### ISSUE THREAD

**Issue by equivalent** [aws/elastic-beanstalk-roadmap#163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**

in `Multicontainer Docker platform (Amazon Linux AMI)` there was an option to provide `essential`  in `Dockerrun.aws.json` so that entire EB docker run script re triggers   if essential container fails. 

Example :

```
{
  "AWSEBDockerrunVersion": 2,

  "containerDefinitions": [
    {
      "name": "background-worker",
      "image": "my-company/my-bg-worker-app",
      "essential": true
    },
    {
      "name": "health_check_nginx",
      "image": "equivalent/health_check_nginx",
      "portMappings": [
        {
          "hostPort": 80,
          "containerPort": 80
        }
      ]
    }
  ]
}
```

>  form [ health_check_nginx_docker ](https://github.com/equivalent/health_check_nginx_docker)

Now that I've switched to  **Docker Amazon Linux 2**  and `docker-compose.yml` there is no option for me to specify  which containers are essential (docker steps for EB should restart)  

Yes `docer-compose.yml` provides [depends_on](https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on) but this will not prompt EB to restart the cycle to try re-up the containers as it was in `Multicontainer Docker Platform`  with Dockerrun file

```
---
version: '3'
services:
  healthcheck:
    image: equivalent/health_check_nginx
    ports:
      - '80:80'
    depends_on:
      - worker
  worker:
    image: myprivateapplicationworker
    environment:
      ROLE: 'worker'
    env_file:
      - .env
```

Nothing will happen if `worker` container dies

**thing to consider**

one way to solve this globally for all EB Linux 2 platforms would be to use `docker-compose up --abort-on-container-exit` (as mentioned in [ this stack overflow issue](https://stackoverflow.com/questions/33799885/how-to-stop-all-containers-when-one-container-stops-with-docker-compose) ) but that may not be the best for all use cases  of all  EB applications
