### ISSUE TITLE
GEOS, PROJ,  Libspatialite Packages Not Available on Amazon Linux 2

### ISSUE THREAD

**Issue by ScottHull** [aws/elastic-beanstalk-roadmap#199]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
I have the following `yum install` instructions in my project's `.ebextensions`:
```
packages:
    yum:
        gcc-c++: []
        libtiff-devel: []
        libjpeg-turbo-devel: []
        sqlite-devel: []
        gdal: []
        gdal-python: []
        geos: []
        proj: []
        libspatialite: []
        libspatialite-devel: []
        libcurl-devel: []
        postgresql93-devel: []
```
The Amazon Linux 1 instances that were recently deprecated had multiple `yum` packages available that are no longer available on Amazon Linux 2 instances.  Geos, Proj,  and Libspatialite are all no longer available in the `yum` package directory and my project can not deploy.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
All Python environments running on AWS Linux 2.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I need these libraries available to me for my project to function on Elastic Beanstalk, as it previously did.

**Are you currently working around this issue?**
I can't until I get these packages available to me.

**Additional context**
None.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by ScottHull** [comment]
I've done some testing and I *think* that the EPEL package repo is not installed by default on Amazon Linux 2 and has to be [installed](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/) (which can be done via commands in `.ebextensions`):
`sudo amazon-linux-extras install epel -y`

That seems to cover everything but `postgresql93-devel`, which is covered in [this StackOverflow thread](https://stackoverflow.com/questions/61148791/postgresql-on-elastic-beanstalk-amazon-linux-2).  Apparently `postgresql93` is old and falls outside of Amazon Linux 2's coverage.  Will see if a newer configuration works with my project:
```
packages:
    yum:
        amazon-linux-extras: []

commands:
    01_postgres_activate:
        command: sudo amazon-linux-extras enable postgresql10
    02_postgres_install:
        command: sudo yum install -y postgresql-devel
```
