### ISSUE TITLE
Automatically authenticate to the Amazon ECR Public registry for image pulls 🇺🇦

### ISSUE THREAD

**Issue by vincentclee** [aws/elastic-beanstalk-roadmap#211]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Currently, Elastic Beanstalk automatically authenticates to the Amazon ECR registry with your environment's instance profile. Requesting this same functionality for Amazon ECR Public registry image pulls.
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker.container.console.html#docker-images

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
[Docker](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.docker)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Following best practices

> We recommend authenticating with your AWS account when pulling images for use on AWS.

https://docs.aws.amazon.com/AmazonECR/latest/public/public-service-quotas.html

**Are you currently working around this issue?**
n/a

**Additional context**
https://aws.amazon.com/about-aws/whats-new/2020/12/announcing-amazon-ecr-public-and-amazon-ecr-public-gallery/
https://docs.aws.amazon.com/AmazonECR/latest/public/public-repositories.html

**Attachments**
**docker-compose.yml**
```yml
version: '3.9'
services:
  datadog-agent:
    image: public.ecr.aws/datadog/agent:7
    environment:
      - DD_API_KEY=
      - DD_APM_ENABLED=true
      - DD_COLLECT_EC2_TAGS=true
      - DD_EC2_PREFER_IMDSV2=true
      - DD_PROCESS_AGENT_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro
```
