### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by IonBazan** [aws/elastic-beanstalk-roadmap#214]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
What do you want us to build?

PHP 8.1 has officially been released on 25 November 2021, yay! Here are the changes and features introduced in this release: https://www.php.net/releases/8.1/en.php. It would be great to see it supported natively by Elastic Beanstalk.

**Are you currently working around this issue?**

Staying on PHP 8.0 or installing the 8.1 manually during startup.

**Comment by faizanakram99** [comment]
I had suggested earlier too that AWS should start working on new PHP version support while it is in beta state, now again we have a new stable PHP version (released one month ago) and there is no news to be seen about PHP 8.1 support.

https://github.com/aws/elastic-beanstalk-roadmap/issues/131#issuecomment-749805846

**Comment by misyaath** [comment]
And also in code build i could not build Laravel 9 because its needed  8.0.2 minimum version  Please update the version  and also i cannot update the version of php in code build environment when i install it dose not update php version

**Comment by kloining** [comment]
@misyaath Take a look at [PHP platform history](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platform-history-php.html)
By using the latest platform, Elastic Beanstalk runs on 8.0.13

**Comment by nickdnk** [comment]
Guys, come on. Assigning **one** person to making sure you have the most recent version of PHP available to your customers can't possibly be this hard.

With all due respect, why does this take so long? You've also sometimes been up to **6 months** behind on security updates for PHP versions you claim to support (7.4 and 8.0 for instance). That's borderline negligent.

**Comment by ghost** [comment]
This is so careless of aws beanstalk team. Such a shame

**Comment by Ciaro** [comment]
[nickdnk](https://github.com/nickdnk) pretty much nailed it with his comment...

**Comment by nickdnk** [comment]
What's the argument here, @devfrey and @axlon? Do you think this is all good or what? Why the downvotes?

**Comment by axlon** [comment]
@nickdnk Because these last few comments add nothing to this thread, regardless of if I agree with them or not. I am subscribed to this thread so that I'd get notified when they finally do decide to address this, but instead every time a notification does pop up its just more of the same.

Regardless, no hard feelings, I think we all want the same thing here.

**Comment by nickdnk** [comment]
@axlon That's fair, but you must also recognize that more complaints about this (and upvotes on the original post don't really generate any noise) should lead to a shift in priority within AWS, despite the fact that they claim it does not. It's not even **on** the roadmap yet or being responded to, even after 4 months and 120+ upvotes, which is ridiculous, to be quite honest.

**Comment by zainspresso** [comment]
For the time being I just do the update myself:
It is ridiculous how long this takes..

```
commands:
  00_upgrade_php:
    command: |
      sudo yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      sudo yum -y install https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      sudo yum -y install yum-utils
      sudo yum -y install rpl
      export LC_ALL=en_US.UTF-8
      export LANG=en_US.UTF-8
      sudo yum-config-manager --disable 'remi-php*'
      sudo yum-config-manager --enable remi-php81
      rpl [remi-php81] "[remi-php81]\npriority=1" /etc/yum.repos.d/remi-php81.repo -e
      yum upgrade -y php php-*
    test: test ! -f .semaphore
  01_lock:
    command: touch .semaphore
```

**Comment by wattsie** [comment]
Hi all,
  I was able to get the code build process working using similar by changing the following...

  You simply need to remove or disable phpenv, then install a newer php with curl and xml then all proceeds as expected.

  PS: you maybe able to just upgrade to 8.0.13, I just went straight to 8.1.

  PPS: also need to change "SolutionStackName" to "64bit Amazon Linux 2 v3.3.11 running PHP 8.0"

Cheers.

buildspec.yml
```
version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.0
    commands:
      - rm -rf $(phpenv root)
      - add-apt-repository ppa:ondrej/php
      - apt-get update
      - apt-get install php8.1 php8.1-xml php8.1-curl -y
      - composer update
  build:
    commands:
      - rm -rf /var/app/current/public/storage
      - php artisan storage:link --force
  post_build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  files:
    - template-export.yml
    - template-configuration.json
```
