### ISSUE TITLE
files key in .ebextensions is ignored

### ISSUE THREAD

**Issue by RaffaeleSgarro** [aws/elastic-beanstalk-roadmap#237]
I need to use the *old* `.ebextensions` in order to create a CloudWatch rule that streams a file to a log group named after the Beanstalk environment name.

It seems that the content of `.ebextensions` (a single `.config` file attached below) is simply ignored:
```yaml
# The structure of this file is documented here:
#   https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html#linux-commands
files:
  "/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/webapp.json":
    mode: "000600"
    owner: root
    group: root
    content: |
      {
        "logs": {
          "logs_collected": {
             "files": {
               "collect_list": [
                 {
                    "file_path": "/home/webapp/logs/webapp.log",
                    "log_group_name": "/aws/elasticbeanstalk/my-env/home/webapp/logs/webapp.log",
                    "log_stream_name": "{instance_id}",
                    "timestamp_format": "%d-%m-%Y %H:%M:%S.%f",
                    "multi_line_start_pattern": "{timestamp_format}"
                 }
               ]
             }
          }
        }
      }
container_commands:
  01_restart_cloudwatch_agent:
    command: systemctl restart amazon-cloudwatch-agent.service
```

**Expected behavior**: connect with SSH and find a file named `/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/webapp.json`

**Actual behavior**: file `/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/webapp.json` does not exist

This is an example Java application that you can use to reproduce the issue:
https://github.com/RaffaeleSgarro/cloudwatch-multiline-log-messages
