### ISSUE TITLE
GRPC with Beanstalk SHARED Application Load Balancer

### ISSUE THREAD

**Issue by alexsanderp** [aws/elastic-beanstalk-roadmap#267]
I can use GRPC with Beanstalk (Application Load Balancer) with the following .ebextension:

```
Resources:
  AWSEBV2LoadBalancerTargetGroup:
    Properties:
      ProtocolVersion: GRPC
      Matcher:
        GrpcCode: "0"
```

But it doesn't work with Shared Application Load Balancer. Because it presents the following error, due to the target group being named in Cloudformation:

```
Updating target group named: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:targetgroup/awseb-pi-facto-default-ycyua/4fa4cf80aa9edbe5 failed Reason: CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename awseb-pi-facto-default-ycyua and update the stack again.
```
