### ISSUE TITLE
.ebextensions seem to be ignored on Amazon Linux 2023

### ISSUE THREAD

**Issue by DimitriosKay** [aws/elastic-beanstalk-roadmap#323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Amazon Linux 2 seems to allow the use of *.config files in an .ebextensions folder to configure the server. It seems these files are not supported in the latest Linux 2023 platform. Not sure if this expands to other language speciic platforms, but this is raised on the basis of PHP. Issue seems to be repeating with every new platform - refer to [189](https://github.com/aws/elastic-beanstalk-roadmap/issues/189#issue-968493190)

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Have found this only on `PHP 8.2 AL2023 version 4.1.0`
Works fine on `64bit Amazon Linux 2 v3.6.0 running PHP 8.1`

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I need to set up an environment in which I can deploy a PHP Symfony app and this requires some server configurations. This can be achieved (and was in previous platform version) using a .config file inside .ebextensions.
For example:
```
commands:
    300-composer-update:
        command: "export COMPOSER_HOME=/root && /usr/bin/composer.phar self-update -n"
container_commands:
    001-composer-install:
        command: "php -d memory_limit=-1 /usr/bin/composer.phar install --optimize-autoloader"
        ignoreErrors: true
```

**Are you currently working around this issue?**
I will have to drop back to AL2, with the caveat of needing to update PHP to 8.2 from 8.1 explicitly, instead of using the latest (longest supported) platform which already provides the latest version anyways.

**Additional context**
Anything else we should know?
N/A

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)
N/A
