### ISSUE TITLE
Enable reference to AWSEBWorkerQueue and AWSEBV2LoadBalancer in a CloudFormation template

### ISSUE THREAD

**Issue by dennisvang** [aws/elastic-beanstalk-roadmap#330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**

It would be great if there were a *simple* way to reference the [`AWSEBWorkerQueue`][2] resource for a `Worker` environment created in a CloudFormation template.

For example, something like `!GetAtt MyWorkerEnvironment.AWSEBWorkerQueue` would be nice.

The docs for [AWS::ElasticBeanstalk::Environment][1] only mention `EndpoinURL` as a return value, so I was silently hoping that `!GetAtt MyWorkerEnvironment.EndpointURL` would return the SQS queue url.  However, unfortunately, stack creation just fails altogether with an error:

>Attribute 'EndpointURL' does not exist

Similarly, being able to access the `AWSEBV2LoadBalancer` for a `WebServer` environment would be of great help in setting up HTTPS configuration.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**

no

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

In a single CloudFormation template that creates both a `WebServer` and a `Worker` environment, I am trying to get the worker's SQS queue url (or name), and assign it to an environment property for the webserver.

Ideally, I would like to be able to use something like `Fn::GetAtt` to get the SQS url from the worker resource, for example:

```yaml
Resources:

  MyWorkerEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    # ...

  MyWebServerEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    DependsOn: MyWorkerEnvironment
    # ...
    Properties:
      # ...
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: WORKER_QUEUE
          Value: !GetAtt MyWorkerEnvironment.AWSEBWorkerQueue  # <-- this would be great, but does not work
```

This seems like a very basic issue that everyone using webservers and workers with cloudformation will run into at some point.

**Are you currently working around this issue?**

I've found, and tested, several alternatives:

- the manual approach: create the stack, copy the SQS queue url, and paste it into an environment property (or hardcode it)
- use an [environment manifest][3] file, i.e. `env.yaml`, to link the environments, as in the [example][4]:
  ```yaml
  AWSConfigurationTemplateVersion: 1.1.0.0
  EnvironmentLinks:
    "WORKER_QUEUE": "<name of my worker environment>"
  ```
- use [`ElasticBeanstalk.Client.describe_environment_resources()`][5] from `boto3` in the app (or use the [aws cli equivalent][9]), for example (simplified):
  ```python
  worker_queue = None
  client = boto3.client('elasticbeanstalk', region_name='eu-west-3')
  response = client.describe_environment_resources(EnvironmentName='<name of my worker env>')
  for queue in response['EnvironmentResources']['Queues']:
      if queue['Name'] == 'WorkerQueue':
          worker_queue = queue['URL']
  ```
- use `.ebextensions` to [export][6] the value of [`AWSEBWorkerQueue`][7] to CloudFormation, then use [`Fn::ImportValue`][8] in the CloudFormation template, as in:

  `.ebextensions/resources.config`
  ```yaml
  Outputs:
    WorkerQueue:
      Description: 'Worker SQS queue'
      Value: { "Ref" : "AWSEBWorkerQueue" }
      Export:
        Name: MyWorkerQueue
  ```
  and in `my-cloudformation-template.yml`
  ```yaml
  # ...
          - Namespace: aws:elasticbeanstalk:application:environment
            OptionName: WORKER_QUEUE
            Value: !ImportValue MyWorkerQueue
  # ...
  ```

These all work, but all suffer from various drawbacks.

I also noticed that the stack created by `AWS::ElasticBeanstalk::Environment` for the worker environment already has an output called `AWSEBWorkerQueueURL`. However, I could not figure out how to get that into my template.

**Additional context**

n/a

**Attachments**

n/a

[1]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticbeanstalk-environment.html#aws-resource-elasticbeanstalk-environment-return-values
[2]: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-format-resources-eb.html
[3]: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-cfg-manifest.html
[4]: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-cfg-links.html
[5]: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/elasticbeanstalk/client/describe_environment_resources.html
[6]: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions-otherkeys.html#ebextensions-otherkeys-outputs
[7]: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-format-resources-eb.html
[8]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html
[9]: https://stackoverflow.com/a/65164776
