### ISSUE TITLE
Add support to enable Proxy Protocol v2 for Network Load Balancers

### ISSUE THREAD

**Issue by myers** [aws/elastic-beanstalk-roadmap#342]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**

We have host a SaSS where each customer needs to be hosted on their own domain.  As a result we terminate our HTTPS traffic on our EB hosts, and use a network load balancer.  We enable the "Proxy Protocol" on our Network LB targets (see https://docs.aws.amazon.com/elasticloadbalancing/latest/network/edit-target-group-attributes.html#proxy-protocol).  It would better if we could at the same time that we add the listeners for 443, that we could say that we want "Proxy Protocol" enabled.

Something like 

`.ebextensions/load-balancer.config`

```
option_settings:
  aws:elasticbeanstalk:environment:process:https:
    Port: '443'
    Protocol: TCP
  aws:elbv2:listener:443:
    DefaultProcess: https
    ListenerEnabled: 'true'
    Protocol: TCP
    # This next line is what this issue is about
    ProxyProtocol: 'true'
```

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

No

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Avoid having to change things in the AWS Console after creating a new environment.

**Are you currently working around this issue?**
How are you currently solving this problem?

After creating a new environment, using AWS Console to enable the option.
